# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravy" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "c9b4b317ff8a8c1796e4dd1a6f83b9555dbb9b027d62b83e6e7b86f7e3973d3c"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "414899031aee71270f5e92b17b8c2c6ed7dd14dcdcf5f288cfaa2c9863e22e49"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "832a56ca535aae833b8ec6f84c528765cc68b65b28dfc91bd3b48baed9eff6aa"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "64e275cf784d730a8cad3583957e7219a314417462aba9bffbe065ee2536e084"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravy"
  desc "A keyboard-first CLI/TUI engineering manager for agentic software development"
  homepage "https://github.com/pot-roast-co/gravy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravy"]
    end
  end

  # No zap stanza required
end
