# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravy" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3e02c7a89bfdaef388a6a705c08f13ee16eed176a7bb64a5961febdd24f13098"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "410489095202b5c3b814b5269ad2b22a0e913a1576a08c84965ef3cf52f07859"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f1bbb19446d76d6db5553909a4711529dfbcc220d7cd22ed5deb44c62802e43f"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8ae93ae27118a3435a012d11ed26e716636cfbc2ad19efee06c21798b98bd5e"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravy"
  desc "A keyboard-first CLI/TUI engineering manager for agentic software development"
  homepage "https://github.com/pot-roast-co/gravy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravy"]
    end
  end

  # No zap stanza required
end
