# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravy" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "534f465102209f3c931446e1939df71619a1322df37f428760e6c1fab93779ab"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "474f657ddf89b788eb4b388a672114b5716aac970d3c4c760d9ef36321c6be37"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "34cde45970fa14232d52e71fdae9324ed72ce324e604e10610958ca5005d62e0"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dcd1c063e089116ccba4e45cb6321e86210aa3dedde9f392b1c9c756ad50855f"
      url "https://github.com/Pot-Roast-Co/gravy/releases/download/v#{version}/gravy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravy"
  desc "A keyboard-first CLI/TUI engineering manager for agentic software development"
  homepage "https://github.com/pot-roast-co/gravy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravy"]
    end
  end

  # No zap stanza required
end
